### ISSUE TITLE
Functionality request

### ISSUE THREAD

**Issue by RaquisDawLn** [PandeoF1/px_botnet#10]
Would you be able to add a xmr miner to the bot with a statistics page on the web panel?

**Comment by PandeoF1** [comment]
Hey, we actually work on a better version of the client. So we think to add a crypto miner. Using a fork that download a simple miner from url and execute it .

**Comment by RaquisDawLn** [comment]
> Hey, we actually work on a better version of the client. So we think to add a crypto miner. Using a fork that download a simple miner from url and execute it .

Will it be on a new repo or updated on this one?

**Comment by PandeoF1** [comment]
On this one

Le mer. 10 août 2022, 02:29, RaquisDawLn ***@***.***> a
écrit :
