### ISSUE TITLE
server api

### ISSUE THREAD

**Issue by CheetoTrump** [PandeoF1/px_botnet#14]
Can you post the api/comms for the server so i can make my own client for it without reading the whole preexisting client?

**Comment by CheetoTrump** [comment]
i.e 
post: 
http://localhost/register?arg=example?arg2=example2 etc
get:
http://localhost/ping?arg=hwid

**Comment by PandeoF1** [comment]
All the program work with one api :
GET | http://localhost/api?id=%random_id%&arch=%arch_of_victim%
It will automaticly add the bot to the database and if the bot has a task it will print the type of the attack, destination....

**Comment by CheetoTrump** [comment]
> All the program work with one api : GET | http://localhost/api?id=%random_id%&arch=%arch_of_victim% It will automaticly add the bot to the database and if the bot has a task it will print the type of the attack, destination....

ok so i have it online and im manually sending the requests, do i need to use a specific user agent to see the tasks? and where in the body will the task be? just plain text or in the headers?

**Comment by PandeoF1** [comment]
Plain text and you don't need a specific user agent (but it's a nice idea).
(For the API it's /api.php but it will change nothing I think)
