### ISSUE TITLE
Methods?

### ISSUE THREAD

**Issue by coolrex330** [PandeoF1/px_botnet#2]
What are the 11 methods listed in the title? (Referring to L7)

**Comment by PandeoF1** [comment]
![Capture d’écran du 2022-06-07 01-40-09](https://user-images.githubusercontent.com/58373303/172266614-ef8f1090-f11a-4fa0-b2ea-95d84a62f018.png)
![Capture d’écran du 2022-06-07 01-40-21](https://user-images.githubusercontent.com/58373303/172266616-e50947a7-a4c7-48f2-a984-0d1299ca0567.png)
Sorry for the reponse time. I haven't receive the notification ^^`.
There is one tcp methods who can use : syn, rst, fin, ack, psh.
