### ISSUE TITLE
Where do I upload the DB and how do i start the server

### ISSUE THREAD

**Issue by abdalmajid77** [PandeoF1/px_botnet#4]
I don't know Where to upload the DB and how to start the server

**Comment by PandeoF1** [comment]
For the database, you need to upload it on a MySQL/mariadb and the server is just an api, so if the website work the api work

**Comment by PandeoF1** [comment]
> I don't know Where to upload the DB and how to start the server
To upload it, use phpmyadmin or in the shell of mysql write :
use db_name
source(s) file.sql;
exit ;

**Comment by abdalmajid77** [comment]
What directory in the mysql my os is debian 11

**Comment by PandeoF1** [comment]
> What directory in the mysql my os is debian 11
> 

Go in the folder of DB in the repository. Write "mysql" in the shell. Write : "create database db_name". Write "use db_name". Write "source file.sql". Write "exit;" and configure the config file of the website.

To create an user if you don't have one :
https://www.digitalocean.com/community/tutorials/how-to-create-a-new-user-and-grant-permissions-in-mysql

**Comment by PandeoF1** [comment]
I have add a docker version for the server. That gonna be more easy for you.
