### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by csenjoyer1337** [PandeoF1/px_botnet#7]
The following error occurs upon attempting to log in:
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/login.php:13) in /var/www/html/login.php on line 67

any fix?

**Comment by PandeoF1** [comment]
We have this error because we use "header("location: path");". With the docker we have this warning because there is some protections from the php container. If you use your own systems that depends on the php version. I gonna make a patch in a few days

**Comment by PandeoF1** [comment]
(Patched)
